services:
  desafiodb:
    image: postgres:latest
    container_name: desafiodb
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    ports:
      - 5435:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
