services:
  desafiodb:
    image: postgres:latest
    container_name: desafiodb
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    ports:
      - 5435:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
    restart: unless-stopped